# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateTimeField(null=True),
        ),
    ]
